### ISSUE TITLE
Syscall.CallAsync should support async natively in neovim

### ISSUE THREAD

**Issue by dbarnett** [google/vim-maktaba#125]
Neovim probably has native asynchronous support, or will eventually have it. In that case, we could detect when we're running in neovim and use native async support directly instead of relying on `vim --remote-expr` to hook back into vim.

Note this might complicate testing since the actual system calls would be different between vim and neovim, but a single vroom file would have to test them both.

**Comment by nicdumz** [comment]
neovim indeed has async support, aka jobcontrol: https://neovim.io/doc/user/job_control.html#job-control
