### ISSUE TITLE
Speed up JSON support for +python

### ISSUE THREAD

**Issue by malcolmr** [google/vim-maktaba#152]
(Split out from #35, which is closed)

We should use Python's `json` library for `maktaba#json#Parse()` and `maktaba#json#Format()` where possible (if Vim is compiled with `+python`). This is both faster and more-correct.

**Comment by malcolmr** [comment]
Status of https://github.com/google/vim-maktaba/compare/master...malcolmr:json right now:

- everything passes except for the error-handling tests.
- I need to either implement something that doesn't depend on `bindeval()` (for Vim < 7.3.569), or make it fall back cleanly to the Vimscript-native version in that case.

# Performance

I tested using:

- a trivial document: `[{"foo": "bar"}]`
- a small document: the first example at http://json.org/example.
- a large document: a 1.7MB extract from https://github.com/lloyd/yajl_vs_rapidjson/blob/master/test_file.json.

I also have a fast machine (i7, lots of RAM, SSD).

## Vimscript 

initialisation (first call to `maktaba#json#Parse('0')`) takes 630μs (median; mean 673.26μs, σ=108.82μs)

- trivial document: parsing 500μs, formatting 116μs
- small document: parsing 3883μs, formatting 777μs
- large document: parsing 345533358μs (346s), formatting 2098024μs (2s)

(all mean values over a large number of runs)

## Python

initialisation takes 6267μs (median; mean 6503.77μs, σ=691.59μs).

- trivial document: parsing 113μs, formatting 35μs
- small document: 182μs, formatting 60μs
- large document: parsing 246202μs (246ms), formatting 141923μs (142ms)

**Comment by dbarnett** [comment]
Nice! The 1000x parsing difference is very clear for the large doc! 6s is some pretty serious initialization time. Wonder if we can get that down, or if it's ameliorated with additional python usage.

For `bindeval()`, seems totally fine to require `+python` AND version >= 7.3.569. Every supported release of Ubuntu has a vim that recent, so we'd be putting effort into a fallback that would make at best a moderate performance improvement for a small number of users.

**Comment by xanderman** [comment]
Just so we're clear. 6267μs is 0.00626s. Those are micros, not millis.

**Comment by dbarnett** [comment]
Oh, oops. Units… how do they work?!

**Comment by malcolmr** [comment]
Okay, everything passes! I'm going to break out one or two other changes first, then try to land the diff above (probably squashed).

nit: Ubuntu 12.04 is still supported, and running 7.3.429. It turns out that we really need at least 7.3.1042, though, as you can't otherwise use a Python `unicode` value as the key in a `vim.Dictionary` before that.

The only open questions (apart from whether I'm doing anything obviously wrong) are:

- Do we want to provide a way to disable this? (I'm thinking yes, if for no other reason than I managed to get Vim to segfault around 7.3.1090 or so due to bugs in Vim). I've added `g:maktaba_disable_json_python_parsing` that will do so, but it's the first flag-like global variable in Maktaba.

- How should we test this? I've currently duplicated `vroom/json.vim` as `vroom/json-vimscript.vim`, which is almost identical. (A few error messages are slightly different.) Is that reasonable, or should I source the bulk of the tests from another file? (`vroom/json-shared.vim.in`?) Or do something else entirely?

**Comment by dbarnett** [comment]
Oh, missed Precise. Guess I saw Saucy was unsupported and stopped looking further back for LTS releases. I couldn't find any stats about # users still on Precise. Worth looking into, but I'd still say wait until someone complains.

Our convention for global library settings is to configure them via functions, like `maktaba#syscall#SetAsyncDisabled()`.

Duplicating the vroom files is fine. Nice to keep the failures in their own file if you run it on a vim without `+python`, and refactoring common bits doesn't seem worth the hit in vroom file complexity.

**Comment by malcolmr** [comment]
Hmm. The difficulty here is that we'd want to set a flag before autoload-ing `maktaba/json.vim`, since we need to control what it does during that.

Okay, I've tried switching to a function defined in `maktaba.vim` (see 3cdce2e), but that brings up another problem: the first thing that `autoload/maktaba.vim` does is to call `maktaba#plugin#GetOrInstall()` on Maktaba's own directory.. which then parses `addon-info.json`, which it'd be sensible to switch to `maktaba#json#Parse()` for... which wouldn't allow any point to call the function before `json.vim` gets autoloaded.

On testing: note that running without `+python` will just test the fallback to the non-Python implementation. I _think_ that's probably useful (vs. forcing the Python version, and then failing).
