### ISSUE TITLE
maktaba#json#Parse fails on neovim

### ISSUE THREAD

**Issue by dbarnett** [google/vim-maktaba#158]
Maktaba is pretty well broken on neovim due to the new maktaba#json#Parse implementation:
```
Error detected while processing function maktaba#plugin#Enter..maktaba#plugin#GetOrInstall..<SNR>6_CreatePluginObject..maktaba#plugin#AddonInfo..maktaba#json#Parse..<SNR>13_PythonParsePartial:
line    2:
AttributeError("'Nvim' object has no attribute 'bindeval'",)
```
`bindeval` is a newer function that neovim hasn't implemented (neovim/neovim#1898), but our vim version check misses the fact that it's neovim and not classic vim.

We should detect `has('nvim')` and either fall back to the pure vimscript implementation for now or add an optimized implementation that works on neovim.

**Comment by dbarnett** [comment]
You can work around this by adding something like this to your (n)vimrc:
```vim
if has('nvim')
  set runtimepath+=path/to/maktaba
  call maktaba#json#python#Disable()
endif
```
NOTE: You need to be careful that `maktaba#json#python#Disable()` is the first maktaba code to execute since maktaba itself uses `maktaba#json#` to read its addon-info.json while bootstrapping itself.

**Comment by dbarnett** [comment]
Or, as mentioned in dupe #159, maybe we can just use vim.eval instead of vim.bindeval? @malcolmr, was there a reason for that decision?

**Comment by ncrowell** [comment]
They probably make the code simpler, since they support direction mutation of Vim list objects: http://vimpluginloader.sourceforge.net/doc/if_pyth.txt.html#python-bindeval.

**Comment by weslem** [comment]
@malcolmr and I talked a little about this already. The two locations where `bindeval()` is used are only pulling data out of fields and then putting data into other fields of a list. `eval()` with string-manipulation should suffice, as no complicated object is manipulated internally.

`eval()` *may* be slower, however. That's the open question Malcom and I didn't resolve.

**Comment by malcolmr** [comment]
I dropped the benchmark script I used to produce the numbers in #152 into https://gist.github.com/malcolmr/a16577c10482b8b48e77. Place it in the same directory as Maktaba's `bootstrap.vim` and run via:

```sh
$ vim -Vvim.log -N -u NONE -S json-benchmark.vim
```

and inspect `vim.log` afterwards.

`test_file.medium.json` was a  1.7MB subset of https://github.com/lloyd/yajl_vs_rapidjson/blob/master/test_file.json containing just the first dictionary entry (`"a"`); the full file took too long for the Vimscript version to load, and I was mostly interesting in comparing the Vimscript and Python versions.

**Comment by dbarnett** [comment]
@malcolmr If you want to drop benchmarking tools into the maktaba repo directly somewhere I'd be strongly in favor. Performance is very important for maktaba development and it's hard to measure objectively.

**Comment by weslem** [comment]
I took a quick look at this today, running @malcomr's benchmarks against a version with `bind()` and `command()` replacing `bindeval()`. Performance was roughly equivalent where I could test, but `Parse` has some complexities I didn't consider earlier.

When returning a complicated dictionary through `command`, one needs to convert the Python dict to a vim-compatible expression string. While possible, there are a lot more nuances here when vim has alternate encoding settings or non-printable characters exist within the JSON.

**Comment by gregorias** [comment]
I tried replacing vim.bindeval with vim.eval, but I think it may be impractical to do so. vim.eval returns a string for objects that are strings or numbers. This means that in format we would need to somehow get information whether given string was a string or a number and it looks like it can't be done without changing specification of vim.eval or maktaba's format. 

I have submitted a PR that checks for nvim and disables python's usage if it is present. Please take a look and comment.
