### ISSUE TITLE
maktaba.Enum and exceptions not working.

### ISSUE THREAD

**Issue by symbolix** [google/vim-maktaba#161]
Hi,

I am experimenting with the examples in *maktaba*, however I have encountered the following issue immediately:

    let g:animals = maktaba#enum#Create(['DUCK', 'PIG', 'COW'])
    echomsg g:animals.Names()

this will error:

    E730: using List as a String

then this goes wrong as well:

   echomsg g:animals.Name(3)

and the error is:

    Error detected while processing function maktaba#enum#Name:
    line    8:
    E605: Exception not caught: ERROR(NotFound): Enum name with value 3.

Any ideas? Thanks.

**Comment by dbarnett** [comment]
Yep, don't use a List as a String. =)
Per `:help :echomsg`:
> The expressions must evaluate to a Number or String, a Dictionary or List causes an error.

You can use `:echo` instead of `:echomsg` and it will work fine.

As for `echomsg g:animals.Name(3)`, that's because the enum is zero-indexed. 0, 1, and 2 work, but 3 correctly throws `ERROR(NotFound)`.

**Comment by symbolix** [comment]
Hi dbarnett,

Thanks for the prompt reply. Sure, I get that in regards to *echomsg*

However, about the other issue. I deliberately violated the index, just to see if the exception will be caught. And it seems like it is not. I get the same ugly vim message that I would get in any other broken function:

    Error detected while processing function maktaba#enum#Name:
    line    8:
    E605: Exception not caught: ERROR(NotFound): Enum name with value 3.

The fact that is says:

    E605: Exception not caught

is a bit alarming?

Thanks,

**Comment by dbarnett** [comment]
> The fact that is says:
> 
>     E605: Exception not caught
> 
> is a bit alarming?

Not really. Functions made to be used by libraries should throw errors so developers can get a stack trace if there's an error. Plugin authors can then translate what thrown errors mean in context into meaningful error messages, like:
```
:MakeSound COW
Moo!
:MakeSound HORSE
ERROR: animal HORSE is not implemented.
```
Which would look something like
```vim
command -nargs=1 MakeSound call s:MakeSound(<f-args>)
function s:MakeSound(animal) abort
  try
    echomsg s:animal_sounds[s:animals.Value(a:animal)]
  catch /ERROR(NotFound):/
    call maktaba#error#Shout('ERROR: Animal %s is not implemented.', a:animal)
  endtry
endfunction
```

**Comment by symbolix** [comment]
Cool, thanks for the explanation. I found out about *vim-maktaba* only today. And I was playing around. The whole framework seems quite complicated at first glance. However, hopefully, I will start figuring things out. It is good to see that the Issues section is active and there are people helping others.

So, thank you very much for your help and for your time.

Just a quick thing, I am after a Logger implementation with vim-maktaba. The included example is quite extensive, however, are you aware of a Logging plugin developed based on the vim-maktaba logging functions?

Thanks,

**Comment by dbarnett** [comment]
Discussed some in #141. We should have a log viewer plugin open sourced before long. It's not a ton of work, just hasn't been a priority yet.

**Comment by symbolix** [comment]
I see, thanks. Looking forward to this. Meanwhile, will try to hack something together, based on the information provided. However, I am not a very experienced vim plugin developer and it would be nice to have a simple case scenario with some nice interface examples for logging.

Thanks,
