### ISSUE TITLE
Doesn't work with dein.vim

### ISSUE THREAD

**Issue by yshui** [google/vim-maktaba#181]
Reports plugin not found when installed using [dein.vim](https://github.com/Shougo/dein.vim)

**Comment by dbarnett** [comment]
I don't know a lot about dein.vim, but you probably just need a `call maktaba#plugin#Detect()` at the end of your plugin installations. Otherwise, if it's something else specific to how dein.vim works, a concrete example might help.

**Comment by yshui** [comment]
Example init.vim:
```vim
set runtimepath^=~/.config/nvim/dein/repos/github.com/Shougo/dein.vim/

call dein#begin(expand('~/.config/nvim/dein/'))

call dein#add('google/vim-maktaba')
call dein#add('google/vim-codefmt')

call dein#end()

if dein#check_install()
  call dein#install()
endif

call maktaba#plugin#Detect()
```
Put dein.vim in ~/.config/nvim/dein/repos/github.com/Shougo/dein.vim/.

The result:
```
Error detected while processing function maktaba#plugin#Get:
line   18:
E605: Exception not caught: ERROR(NotFound): Plugin codefmt
E605: Exception not caught: ERROR(NotFound): Plugin codefmt
Press ENTER or type command to continue
```

**Comment by dbarnett** [comment]
What is the full `runtimepath` at the beginning and end of that vimrc snippet? What does `:echo maktaba#plugin#RegisteredPlugins()` output?

Does seem like an issue with paths and directory names and potentially specific to dein.vim.

**Comment by yshui** [comment]
At the beginning:
```vim
runtimepath=~/.config/nvim,/etc/xdg/nvim,~/.local/share/nvim/site,/usr/local/share/nvim/site,/usr/share/nvim/site,/usr/share/nvim/runtime,/usr/share/nvim/site/after,/usr/local/share/nvim/site/after,~/.local/share/nvim/site/after,/etc/xdg/nvim/after,~/.config/nvim/after
```
At the end:
```vim
runtimepath=~/.config/nvim/dein/repos/github.com/Shougo/dein.vim/,~/.config/nvim,/etc/xdg/nvim,~/.local/share/nvim/site,/usr/local/share/nvim/site,~/.config/nvim/dein/.cache/init.vim/.dein,/usr/share/nvim/site,/usr/share/nvim/runtime,~/.config/nvim/dein/.cache/init.vim/.dein/after,/usr/share/nvim/site/after,/usr/local/share/nvim/site/after,~/.local/share/nvim/site/after,/etc/xdg/nvim/after,~/.config/nvim/after
```
```:echo maktaba#plugin#RegisteredPlugins()```: ```['dein', 'maktaba', 'nvim', 'site']```

**Comment by yshui** [comment]
dein.vim merge all plugins into one directory.

Guess it's impossible to work with that? Why does maktaba need to know which individual plugins are installed?

**Comment by dbarnett** [comment]
Pretty hard to work with that, yeah. How does it handle conflicting file paths, like two plugins with a `plugin/foo.vim`? And… why?

Maktaba uses an object per plugin to be able to store flag values, manually source certain files, etc. I could imagine rethinking how it handles that 1:1 mapping, but it would be a major undertaking if it's even feasible. =(

**Comment by dbarnett** [comment]
I do see it has a `merged` option (`:help dein-options-merged`) that looks relevant. You could try disabling that on affected plugins and see if it works around the issue:
```vim
call dein#add('google/vim-maktaba', {'merged': 0})
call dein#add('google/vim-codefmt', {'merged': 0})
```

**Comment by yshui** [comment]
@dbarnett  
> And… why?

I assume that's for performance.

> I do see it has a merged option

Yes, that's the workaround I was talking about =)
