### ISSUE TITLE
Broken links in Wiki

### ISSUE THREAD

**Issue by omrisarig13** [google/vim-maktaba#226]
I was reading the Wiki file of [Creating Vim Plugins with Maktaba](https://github.com/google/vim-maktaba/wiki/Creating-Vim-Plugins-with-Maktaba) and came across two broken links (links that are no longer exist).

The links are:

- Vimscript Style Guide.
  - current link: http://google-styleguide.googlecode.com/svn/trunk/vimscriptguide.xml
  - right link: https://google.github.io/styleguide/vimscriptguide.xml
- Full Vimscript Guide
   - current link: http://google-styleguide.googlecode.com/svn/trunk/vimscriptfull.xml
   - right link: https://google.github.io/styleguide/vimscriptfull.xml

(I am not sure about the right links, but it seems like the same documents).

I don't know if it is possible to open a pull request for Wiki changes. If it is, I am willing to fix the links and create a relevant pull request.

**Comment by dbarnett** [comment]
Fixed. Thanks for pointing that out.
