### ISSUE TITLE
Error formatting file: ERROR(NotFound): Python module maktaba

### ISSUE THREAD

**Issue by priyanshu219** [google/vim-maktaba#231]
When I type **:FormatCode**, it shows the above error 
How to resolve it?

**Comment by dbarnett** [comment]
I wonder: are you using a +python2 or python-2-and-3 build of vim? I haven't seen issues with automatically loading the python module before but it's possible something is silently blowing up for a particular python version.

Do you see any interesting output if you execute
```vim
:echo maktaba#python#ImportModule(maktaba#Maktaba(), 'maktaba')
```
?

**Comment by priyanshu219** [comment]
I **reinstalled** all the plugins and this time they work fine
So, honestly, I don't whats happened? 

By the way **thanks** for your support :)

**Comment by dbarnett** [comment]
FYI I improved the error output so if you update and you run into more issues like this in the future it should give you a more useful error message you can post. One issue I'm fixing seems to be a python 3.8 compatibility change (plus neovim apparently choking on python warnings).
