### ISSUE TITLE
Maktaba plugin bootstrap can fail with `Unknown function: maktaba#Maktaba`

### ISSUE THREAD

**Issue by dbarnett** [google/vim-maktaba#239]
I ran into some strange initialization failures for the maktaba plugin when trying to bootstrap another plugin for testing. The error is `Unknown function: maktaba#Maktaba` and seems to be caused by a sort of circular dependency during setup. Not sure yet what specific circumstances make it blow up or not, since it's clearly not happening in day-to-day usage.

The failure scenario is:

1. Calling an autoload function like `maktaba#IsAtLeastVersion` tries to load autoload/maktaba.vim and maktaba tries to `GetOrInstall` itself at https://github.com/google/vim-maktaba/blob/46730b0d818da2da005e3c8a38ff987a2dd36d7c/autoload/maktaba.vim#L26
2. That sources autoload/maktaba/plugin.vim which tries to call `maktaba#Maktaba`: https://github.com/google/vim-maktaba/blob/46730b0d818da2da005e3c8a38ff987a2dd36d7c/autoload/maktaba/plugin.vim#L903
3. The call to `maktaba#Maktaba()` fails because vim is still in the middle of sourcing autoload/maktaba.vim from the first step. It hasn't gotten through the definition of `maktaba#Maktaba()` or the `s:plugin` variable it needs.

**Comment by dbarnett** [comment]
It might depend on vim version. I was seeing it after some bootstrap.vim changes in https://github.com/bazelbuild/vim-bazel/commit/905478a097545a30d2def69bb004568f5066f902 when I ran vroom locally, but *NOT* when I ran it via Travis CI, and also *NOT* when I ran neovim mode.

**Comment by malcolmr** [comment]
Looking at this today with @snu5mumr1k, it seems like a plausible fix might be:

1. Move the definition of `maktaba#Maktaba()` up within `autoload/maktaba.vim` so that it's available immediately, before the call to `maktaba#plugin#GetOrInstall()`. This will require doing something like `let s:maktaba = 0` at global scope first to make that variable defined, albeit with a temporary invalid value.
2. Add something like `maktaba#plugin#InternalInstallMaktaba(dir)` for bootstrapping that does something like:
    ```viml
    let s:maktaba = maktaba#plugin#GetOrInstall(s:plugindir)
    return s:maktaba
    ```
    to overwrite the value of `s:maktaba` set in `autoload/maktaba/plugin.vim` by the call to `maktaba#Maktaba()` during its initial load.
3. Call that new function inside `autoload/maktaba.vim` instead of the generic `maktaba#plugin#GetOrInstall()`.

**Comment by dbarnett** [comment]
SG except that instead of using a temporary value of `0`, we should probably use a minimal dict that we can hopefully update in-place, so that anything internal that does save the output of `maktaba#Maktaba()` in the meantime isn't permanently stuck with a dummy value.

**Comment by malcolmr** [comment]
I was actually thinking the other way around: using `0` means that it'll be completely obvious if anyone tries to use a partial/invalid value (which I don't think they do, fortunately).

However, you make a good point, as we could perhaps simplify this with just `autoload/maktaba.vim` looking like:

```viml
let s:maktaba = {}

""
" Returns a handle to the maktaba plugin object.
function! maktaba#Maktaba() abort
  return s:maktaba
endfunction

let s:plugindir =  expand('<sfile>:p:h:h')
if !exists('s:maktaba')
  call extend(s:maktaba, maktaba#plugin#GetOrInstall(s:plugindir))
  let s:maktaba.globals.installers = []
  let s:maktaba.globals.loghandlers = maktaba#reflist#Create()
endif
```

(entirely untested though)

**Comment by dbarnett** [comment]
You're right, there are cons either way. IIUC we can't actually guarantee the placeholder value never gets used the way the circular dependency works so I was looking to make it try hard to recover, but it's also possible it'll still fail and just be all the harder to troubleshoot. :shrug:

Another possibility would be to change the `maktaba#plugin` file to move the `s:maktaba` setup inside functions and have them call `maktaba#Maktaba()` on demand.
