### ISSUE TITLE
Provide polyfill for pyeval

### ISSUE THREAD

**Issue by xanderman** [google/vim-maktaba#70]
pyeval was added in 7.3.569, and is a much better way of getting the result of a single python statement into a ViM data type than eval(maktaba#command#GetOutput('python print …')). We should provide something like maktaba#python#Eval or maktaba#command#PyEval. http://stackoverflow.com/a/13220941/286583 suggests it look like:

``` vim
function Pyeval(expr)
    python import json
    python vim.command('return '+json.dumps(eval(vim.eval('a:expr'))))
endfunction
```

**Comment by dbarnett** [comment]
I had a need for this in google/vim-coverage#8 (Travis's vim version is older than pyeval and I wanted those tests to pass as-is). Temporarily inlined it there so I wasn't blocked on maktaba version updates and I could beta test it in that plugin.

Will add an implementation in maktaba and after a while cut vim-coverage over to this implementation.
